name: lh-tactics-test
version: 0.1.0.0
github: "githubuser/lh-tactics-test"
license: BSD3
author: "Henry Blanchette"
maintainer: "blancheh@umd.edu"
copyright: "2022 Henry Blanchette"

extra-source-files:
  - README.md
  - ChangeLog.md

description:
  Please see the README on GitHub at
  <https://github.com/githubuser/lh-tactics-test#readme>

dependencies:
  - liquidhaskell == 0.8.10.7
  - liquid-base == 4.15.0.0
  - template-haskell == 2.17.0.0
  - lh-tactics == 0.1.0.28
  - containers

library:
  source-dirs: src
  # ghc-options:
  #   - -fplugin=LiquidHaskell
  #   - -fplugin-opt=LiquidHaskell:--reflection
  #   - -fplugin-opt=LiquidHaskell:--ple-local
  #   - -ddump-splices
